stages:
  download:
    cmd: bash stages/01_download.sh
    deps:
      - stages/01_download.sh
    outs:
      - download

  build:
    cmd: .venv/bin/python stages/03_build.py
    deps:
      - stages/03_build.py
      - download
    outs:
      - brick
